title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     LearnNow
  repo:     LearnerRepo

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: main
    else:
      - type: respond
        with: 01_try-again.md
      - type: respond
        with: 01_nice-work.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
Step 1
- title: S1
  description: This is step 1
  event: push
  actions: 
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: add name to README
    else:
      - type: respond
        with: 01_try-again.md

  - type: respond
    with: 01_nice-work.md

- title: Assign yourself
  description: Assign the first issue to yourself.
  event: issues.assigned
  link: 'https://github.com/XLJasonHuo/lab-starter/issues/1'
  actions:
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: main
    else:
    - type: respond
      with: 01_try-again.md
  
  - type: respond
  with: 01_nice-work.md


# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
title: S2
description: This is step 2
event: push
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 3
title: S3
description: This is step 3
event: push
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 4
title: S4
description: This is step 4
event: push
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

Step 5
title: S5
description: This is step 5
event: push
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

